android: static libav build
Fix linux build error:
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/libfreetype.so: undefined reference to symbol 'BZ2_bzDecompress'
/usr/bin/ld: /lib/x86_64-linux-gnu/libbz2.so.1.0: error adding symbols: DSO missing from command line